import type { Destination, Tour, TourItinerary, TourGuide, Testimonial, BlogPost, TeamMember, Faq } from "@shared/schema";

// Sample destinations data
export const sampleDestinations: Destination[] = [
  {
    id: "1",
    name: "Bali",
    country: "Indonesia",
    continent: "asia",
    description: "Experience the magical island of Bali with its stunning temples, rice terraces, and pristine beaches. Discover ancient Hindu culture, vibrant nightlife, and world-class surfing spots.",
    shortDescription: "Tropical paradise with temples and beaches",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    rating: 4.9,
    reviewCount: 2847,
    priceFrom: 899,
    featured: true,
    trending: true,
    popular: true,
    isNew: false,
  },
  {
    id: "2",
    name: "Santorini",
    country: "Greece",
    continent: "europe",
    description: "Explore the iconic white-washed buildings and blue domes of Santorini. Watch breathtaking sunsets over the caldera, sample local wines, and discover ancient ruins.",
    shortDescription: "Iconic Greek island with stunning sunsets",
    imageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800",
    rating: 4.8,
    reviewCount: 3156,
    priceFrom: 1299,
    featured: true,
    trending: false,
    popular: true,
    isNew: false,
  },
  {
    id: "3",
    name: "Maldives",
    country: "Maldives",
    continent: "asia",
    description: "Indulge in the ultimate luxury escape in the Maldives. Crystal clear waters, overwater bungalows, and world-class diving make this the perfect honeymoon destination.",
    shortDescription: "Luxury overwater villas in crystal waters",
    imageUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
    rating: 4.9,
    reviewCount: 1923,
    priceFrom: 2499,
    featured: true,
    trending: true,
    popular: true,
    isNew: false,
  },
  {
    id: "4",
    name: "Swiss Alps",
    country: "Switzerland",
    continent: "europe",
    description: "Discover the majestic Swiss Alps with breathtaking mountain scenery, charming villages, and world-class skiing. Experience Swiss precision and natural beauty.",
    shortDescription: "Majestic mountains and alpine villages",
    imageUrl: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800",
    rating: 4.7,
    reviewCount: 2134,
    priceFrom: 1799,
    featured: false,
    trending: false,
    popular: true,
    isNew: true,
  },
  {
    id: "5",
    name: "Tokyo",
    country: "Japan",
    continent: "asia",
    description: "Immerse yourself in the fascinating blend of ultra-modern and traditional Japan. From ancient temples to neon-lit streets, Tokyo offers endless discoveries.",
    shortDescription: "Ancient traditions meet futuristic innovation",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    rating: 4.8,
    reviewCount: 4521,
    priceFrom: 1599,
    featured: true,
    trending: true,
    popular: true,
    isNew: false,
  },
  {
    id: "6",
    name: "Machu Picchu",
    country: "Peru",
    continent: "south-america",
    description: "Trek to the ancient Incan citadel of Machu Picchu. This UNESCO World Heritage site offers breathtaking views and a glimpse into Peru's rich history.",
    shortDescription: "Ancient Incan citadel in the clouds",
    imageUrl: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800",
    rating: 4.9,
    reviewCount: 2876,
    priceFrom: 1899,
    featured: true,
    trending: false,
    popular: true,
    isNew: false,
  },
  {
    id: "7",
    name: "Safari Kenya",
    country: "Kenya",
    continent: "africa",
    description: "Witness the incredible wildlife of Kenya on an unforgettable safari adventure. See the Big Five and experience the great migration in the Masai Mara.",
    shortDescription: "Wildlife safari and the great migration",
    imageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800",
    rating: 4.8,
    reviewCount: 1654,
    priceFrom: 2199,
    featured: false,
    trending: true,
    popular: false,
    isNew: true,
  },
  {
    id: "8",
    name: "Dubai",
    country: "UAE",
    continent: "asia",
    description: "Experience the glamour and innovation of Dubai. From the world's tallest building to luxury shopping and desert adventures, Dubai has it all.",
    shortDescription: "Luxury, innovation, and desert adventures",
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    rating: 4.7,
    reviewCount: 3892,
    priceFrom: 1399,
    featured: false,
    trending: true,
    popular: true,
    isNew: false,
  },
  {
    id: "9",
    name: "New Zealand",
    country: "New Zealand",
    continent: "oceania",
    description: "Explore the stunning landscapes of New Zealand, from majestic fjords to volcanic wonders. Perfect for adventure seekers and nature lovers alike.",
    shortDescription: "Epic landscapes and adventure sports",
    imageUrl: "https://images.unsplash.com/photo-1469521669194-babb45599def?w=800",
    rating: 4.9,
    reviewCount: 1876,
    priceFrom: 2299,
    featured: false,
    trending: false,
    popular: true,
    isNew: true,
  },
];

// Sample tours data
export const sampleTours: Tour[] = [
  {
    id: "1",
    title: "Bali Bliss: Temples & Beaches",
    destinationId: "1",
    description: "Embark on an unforgettable journey through Bali's most iconic destinations. From the sacred Uluwatu Temple perched on dramatic cliffs to the serene rice terraces of Tegallalang, this tour captures the essence of the Island of Gods. Relax on pristine beaches, explore vibrant markets, and immerse yourself in Balinese culture.",
    shortDescription: "7-day cultural and beach experience in Bali",
    duration: "7 Days / 6 Nights",
    price: 1299,
    originalPrice: 1599,
    rating: 4.9,
    reviewCount: 847,
    maxGroupSize: 12,
    spotsLeft: 4,
    category: "adventure",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    galleryImages: [
      "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800",
      "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800",
      "https://images.unsplash.com/photo-1573790387438-4da905039392?w=800",
    ],
    inclusions: [
      "Airport transfers",
      "6 nights accommodation",
      "Daily breakfast",
      "Professional English-speaking guide",
      "All entrance fees",
      "Traditional dance show",
    ],
    exclusions: [
      "International flights",
      "Travel insurance",
      "Personal expenses",
      "Optional activities",
    ],
    highlights: [
      "Watch sunrise at Mount Batur",
      "Explore Ubud's art markets",
      "Visit ancient Tirta Empul Temple",
      "Surf lessons at Kuta Beach",
    ],
    featured: true,
  },
  {
    id: "2",
    title: "Santorini Romantic Escape",
    destinationId: "2",
    description: "Experience the romance of Santorini with this carefully curated getaway. Wander through the charming streets of Oia, watch world-famous sunsets, and discover hidden beaches. This tour combines relaxation with exploration, perfect for couples seeking an unforgettable Mediterranean experience.",
    shortDescription: "5-day romantic getaway in the Greek Islands",
    duration: "5 Days / 4 Nights",
    price: 1899,
    originalPrice: 2299,
    rating: 4.8,
    reviewCount: 623,
    maxGroupSize: 8,
    spotsLeft: 2,
    category: "honeymoon",
    imageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800",
    galleryImages: [
      "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800",
      "https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800",
      "https://images.unsplash.com/photo-1601581875039-e899893d520c?w=800",
    ],
    inclusions: [
      "Luxury cave hotel accommodation",
      "Private airport transfers",
      "Daily gourmet breakfast",
      "Wine tasting tour",
      "Sunset sailing cruise",
      "Couples spa treatment",
    ],
    exclusions: [
      "Flights",
      "Travel insurance",
      "Lunch and dinner",
      "Personal expenses",
    ],
    highlights: [
      "Private sunset dinner in Oia",
      "Catamaran cruise around the caldera",
      "Wine tasting at local vineyards",
      "Explore ancient Akrotiri ruins",
    ],
    featured: true,
  },
  {
    id: "3",
    title: "Maldives Luxury Retreat",
    destinationId: "3",
    description: "Indulge in the ultimate luxury at an exclusive Maldives resort. Stay in stunning overwater villas, snorkel with manta rays, and enjoy world-class dining. This all-inclusive package offers the perfect blend of relaxation and adventure in paradise.",
    shortDescription: "6-day all-inclusive luxury beach escape",
    duration: "6 Days / 5 Nights",
    price: 3999,
    originalPrice: 4799,
    rating: 4.9,
    reviewCount: 412,
    maxGroupSize: 6,
    spotsLeft: 3,
    category: "luxury",
    imageUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
    galleryImages: [
      "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800",
      "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800",
      "https://images.unsplash.com/photo-1540202404-1b927e27fa8b?w=800",
    ],
    inclusions: [
      "Overwater villa accommodation",
      "Speedboat transfers",
      "All meals and premium drinks",
      "Snorkeling equipment",
      "Sunset dolphin cruise",
      "Private beach dinner",
    ],
    exclusions: [
      "International flights",
      "Spa treatments",
      "Diving excursions",
      "Travel insurance",
    ],
    highlights: [
      "Stay in overwater bungalow",
      "Swim with manta rays",
      "Underwater restaurant dining",
      "Private sandbank picnic",
    ],
    featured: true,
  },
  {
    id: "4",
    title: "Japan Cultural Discovery",
    destinationId: "5",
    description: "Journey through Japan's rich cultural heritage and modern marvels. From the ancient temples of Kyoto to the bustling streets of Tokyo, experience the perfect blend of tradition and innovation. This comprehensive tour covers Japan's most iconic destinations.",
    shortDescription: "10-day journey through ancient and modern Japan",
    duration: "10 Days / 9 Nights",
    price: 2799,
    originalPrice: 3299,
    rating: 4.8,
    reviewCount: 892,
    maxGroupSize: 14,
    spotsLeft: 6,
    category: "cultural",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    galleryImages: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800",
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800",
      "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800",
    ],
    inclusions: [
      "JR Pass (7 days)",
      "Traditional ryokan stay",
      "Daily breakfast",
      "Tea ceremony experience",
      "Sumo tournament tickets",
      "Local guide in each city",
    ],
    exclusions: [
      "International flights",
      "Lunch and dinner",
      "Optional activities",
      "Travel insurance",
    ],
    highlights: [
      "Stay in a traditional ryokan",
      "Visit Fushimi Inari shrine",
      "Experience a tea ceremony",
      "Bullet train adventure",
    ],
    featured: true,
  },
  {
    id: "5",
    title: "African Safari Adventure",
    destinationId: "7",
    description: "Witness the raw beauty of African wildlife on this unforgettable safari experience. Track the Big Five through the Masai Mara, meet local Maasai warriors, and sleep under the stars in luxury tented camps. A once-in-a-lifetime adventure awaits.",
    shortDescription: "8-day wildlife safari in Kenya",
    duration: "8 Days / 7 Nights",
    price: 3499,
    originalPrice: 3999,
    rating: 4.9,
    reviewCount: 567,
    maxGroupSize: 8,
    spotsLeft: 5,
    category: "wildlife",
    imageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800",
    galleryImages: [
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800",
      "https://images.unsplash.com/photo-1549366021-9f761d450615?w=800",
      "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800",
    ],
    inclusions: [
      "Luxury tented camp stays",
      "All game drives",
      "Park entrance fees",
      "Professional safari guide",
      "Full board meals",
      "Maasai village visit",
    ],
    exclusions: [
      "International flights",
      "Visa fees",
      "Tips and gratuities",
      "Travel insurance",
    ],
    highlights: [
      "Big Five game viewing",
      "Hot air balloon safari",
      "Maasai cultural experience",
      "Witness the great migration",
    ],
    featured: true,
  },
  {
    id: "6",
    title: "Machu Picchu Trek",
    destinationId: "6",
    description: "Embark on the classic Inca Trail to Machu Picchu, one of the world's most iconic treks. Walk in the footsteps of ancient Incas, passing through cloud forests and ancient ruins before reaching the majestic citadel at sunrise.",
    shortDescription: "5-day Inca Trail adventure to the lost city",
    duration: "5 Days / 4 Nights",
    price: 1699,
    originalPrice: 1999,
    rating: 4.9,
    reviewCount: 734,
    maxGroupSize: 10,
    spotsLeft: 3,
    category: "adventure",
    imageUrl: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800",
    galleryImages: [
      "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800",
      "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=800",
      "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800",
    ],
    inclusions: [
      "Inca Trail permit",
      "Professional trekking guide",
      "Camping equipment",
      "All meals during trek",
      "Porter service",
      "Machu Picchu entrance",
    ],
    exclusions: [
      "Flights to Cusco",
      "Sleeping bag rental",
      "Tips for guides/porters",
      "Travel insurance",
    ],
    highlights: [
      "Trek the famous Inca Trail",
      "Sunrise at Sun Gate",
      "Explore Machu Picchu",
      "Visit ancient Incan ruins",
    ],
    featured: false,
  },
];

// Sample itineraries
export const sampleItineraries: TourItinerary[] = [
  {
    id: "1",
    tourId: "1",
    day: 1,
    title: "Arrival in Bali",
    description: "Welcome to Bali! Upon arrival at Ngurah Rai International Airport, you'll be greeted by your guide and transferred to your hotel in Seminyak. Settle in and enjoy the evening at leisure.",
    activities: ["Airport pickup", "Hotel check-in", "Welcome dinner"],
  },
  {
    id: "2",
    tourId: "1",
    day: 2,
    title: "Uluwatu Temple & Beaches",
    description: "Explore the stunning clifftop Uluwatu Temple and watch the famous Kecak fire dance at sunset. Spend the afternoon relaxing on pristine beaches.",
    activities: ["Visit Uluwatu Temple", "Kecak dance performance", "Beach time at Padang Padang"],
  },
  {
    id: "3",
    tourId: "1",
    day: 3,
    title: "Ubud Art & Culture",
    description: "Journey to the cultural heart of Bali. Visit the Ubud Monkey Forest, explore local art galleries, and walk through the famous Tegallalang Rice Terraces.",
    activities: ["Monkey Forest visit", "Art market exploration", "Rice terrace trek"],
  },
  {
    id: "4",
    tourId: "1",
    day: 4,
    title: "Mount Batur Sunrise",
    description: "Wake early for a magical sunrise trek to Mount Batur. Witness the stunning sunrise over the caldera lake before enjoying breakfast with a view.",
    activities: ["Sunrise trek", "Volcanic breakfast", "Hot springs relaxation"],
  },
];

// Sample tour guides
export const sampleGuides: TourGuide[] = [
  {
    id: "1",
    name: "Made Wijaya",
    title: "Senior Cultural Guide",
    bio: "With over 15 years of experience guiding visitors through Bali's sacred sites and hidden gems, Made brings an unmatched depth of knowledge about Balinese culture and traditions.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    languages: ["English", "Indonesian", "Japanese"],
    experience: 15,
    rating: 4.9,
  },
  {
    id: "2",
    name: "Elena Papadopoulos",
    title: "Greece Specialist",
    bio: "Born and raised in Santorini, Elena shares her love for Greek history, mythology, and cuisine with every tour. Her passion for her homeland is contagious.",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    languages: ["English", "Greek", "Italian"],
    experience: 10,
    rating: 4.8,
  },
];

// Sample testimonials
export const sampleTestimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    location: "New York, USA",
    imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
    rating: 5,
    review: "Our Bali trip exceeded all expectations! The guides were incredibly knowledgeable, and every detail was perfectly planned. The sunrise trek to Mount Batur was absolutely magical.",
    tourId: "1",
    destinationName: "Bali",
    featured: true,
  },
  {
    id: "2",
    name: "James & Emma Wilson",
    location: "London, UK",
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
    rating: 5,
    review: "The Santorini honeymoon package was pure romance. From the cave hotel to the sunset cruise, everything was flawless. We can't wait to book our next adventure!",
    tourId: "2",
    destinationName: "Santorini",
    featured: true,
  },
  {
    id: "3",
    name: "Raj Patel",
    location: "Mumbai, India",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
    rating: 5,
    review: "The African safari was a dream come true. Seeing the great migration up close and staying in the luxury camps was an experience I'll cherish forever.",
    tourId: "5",
    destinationName: "Kenya",
    featured: true,
  },
  {
    id: "4",
    name: "Yuki Tanaka",
    location: "Tokyo, Japan",
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
    rating: 5,
    review: "I traveled solo to Machu Picchu and felt completely safe and supported throughout. The trek was challenging but so rewarding. Best travel decision ever!",
    tourId: "6",
    destinationName: "Peru",
    featured: true,
  },
  {
    id: "5",
    name: "Michael & Lisa Brown",
    location: "Sydney, Australia",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    rating: 5,
    review: "The Maldives exceeded our wildest dreams. The overwater villa was stunning, and the staff made us feel like royalty. Pure paradise!",
    tourId: "3",
    destinationName: "Maldives",
    featured: true,
  },
  {
    id: "6",
    name: "Hans Mueller",
    location: "Berlin, Germany",
    imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
    rating: 5,
    review: "The Japan tour was incredibly well organized. From the ryokan stay to the tea ceremony, every cultural experience was authentic and memorable.",
    tourId: "4",
    destinationName: "Japan",
    featured: false,
  },
];

// Sample blog posts
export const sampleBlogPosts: BlogPost[] = [
  {
    id: "1",
    title: "10 Hidden Gems in Bali You Need to Visit",
    slug: "hidden-gems-bali",
    excerpt: "Discover the secret spots that most tourists miss. From hidden waterfalls to secluded temples, these are the places locals love.",
    content: "Full article content here...",
    imageUrl: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800",
    category: "Destinations",
    author: "Emma Thompson",
    authorImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    readTime: 8,
    publishedAt: new Date("2024-01-15"),
    featured: true,
  },
  {
    id: "2",
    title: "Ultimate Packing Guide for Adventure Travel",
    slug: "adventure-packing-guide",
    excerpt: "Pack smart, travel light. Here's everything you need for your next adventure without overpacking.",
    content: "Full article content here...",
    imageUrl: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800",
    category: "Travel Tips",
    author: "David Chen",
    authorImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    readTime: 6,
    publishedAt: new Date("2024-01-10"),
    featured: true,
  },
  {
    id: "3",
    title: "Best Time to Visit Each Continent",
    slug: "best-time-to-visit",
    excerpt: "Plan your trips perfectly with our seasonal guide to every corner of the globe.",
    content: "Full article content here...",
    imageUrl: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=800",
    category: "Planning",
    author: "Sophie Anderson",
    authorImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    readTime: 10,
    publishedAt: new Date("2024-01-05"),
    featured: false,
  },
];

// Sample team members
export const sampleTeamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Alexandra Chen",
    role: "Founder & CEO",
    bio: "With 20+ years in the travel industry, Alex founded Wanderlust Tours to share her passion for authentic travel experiences with the world.",
    imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400",
    linkedIn: "https://linkedin.com",
    twitter: "https://twitter.com",
  },
  {
    id: "2",
    name: "Marcus Johnson",
    role: "Head of Operations",
    bio: "Marcus ensures every trip runs smoothly, from the first inquiry to the farewell airport transfer. He's visited 65 countries and counting.",
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400",
    linkedIn: "https://linkedin.com",
    twitter: null,
  },
  {
    id: "3",
    name: "Priya Sharma",
    role: "Lead Travel Designer",
    bio: "Priya crafts bespoke itineraries that balance must-see highlights with off-the-beaten-path discoveries. Every trip she designs is unique.",
    imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400",
    linkedIn: "https://linkedin.com",
    twitter: "https://twitter.com",
  },
  {
    id: "4",
    name: "Tom Williams",
    role: "Customer Experience Manager",
    bio: "Tom leads our 24/7 support team, ensuring travelers have assistance whenever they need it, wherever they are in the world.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    linkedIn: "https://linkedin.com",
    twitter: null,
  },
];

// Sample FAQs
export const sampleFaqs: Faq[] = [
  {
    id: "1",
    question: "How far in advance should I book my tour?",
    answer: "We recommend booking at least 2-3 months in advance, especially for popular destinations during peak season. Some tours, like the Inca Trail, require booking 6+ months ahead due to permit limitations.",
    category: "booking",
    tourId: null,
  },
  {
    id: "2",
    question: "What is your cancellation policy?",
    answer: "Full refund if cancelled 60+ days before departure. 50% refund for cancellations 30-59 days before. No refund for cancellations less than 30 days before departure. We strongly recommend travel insurance.",
    category: "booking",
    tourId: null,
  },
  {
    id: "3",
    question: "Are your tours suitable for solo travelers?",
    answer: "Absolutely! Many of our travelers are solo adventurers. Our small group tours are perfect for meeting like-minded travelers. We also offer private tours if you prefer a more personalized experience.",
    category: "general",
    tourId: null,
  },
  {
    id: "4",
    question: "What's included in the tour price?",
    answer: "Each tour lists specific inclusions, but generally this covers accommodation, transportation, listed activities, entrance fees, and some meals. International flights and travel insurance are typically not included.",
    category: "pricing",
    tourId: null,
  },
  {
    id: "5",
    question: "Do I need travel insurance?",
    answer: "Yes, comprehensive travel insurance is mandatory for all our tours. It should cover trip cancellation, medical emergencies, and evacuation. We can recommend trusted insurance providers.",
    category: "general",
    tourId: null,
  },
];

// Stats for Why Choose Us section
export const companyStats = {
  destinations: 500,
  happyTravelers: 50000,
  tourGuides: 200,
  yearsExperience: 15,
};

// Company contact info
export const companyInfo = {
  phone: "+1 (800) 123-4567",
  email: "hello@wanderlusttours.com",
  whatsapp: "+1 (800) 123-4567",
  address: "123 Adventure Lane, Travel City, TC 12345",
  officeHours: "Mon-Fri: 9AM-8PM | Sat-Sun: 10AM-6PM",
  socialMedia: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    twitter: "https://twitter.com",
    youtube: "https://youtube.com",
  },
};
